import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { buildSystemPrompt, buildVoiceCommandPrompt } from '@/lib/prompts'
import { checkRateLimit, getClientIp } from '@/lib/rateLimit'
import {
  PHI4_RATE_LIMIT,
  PHI4_RATE_WINDOW_MS,
  PHI4_MAX_PAYLOAD_BYTES,
  PHI4_MAX_TOKENS_HARD_CAP,
  PHI4_DEFAULT_MAX_TOKENS,
  PHI4_DEFAULT_DEPLOYMENT,
} from '@/lib/constants'
import type { Language } from '@/lib/types'

export async function POST(req: NextRequest) {
  // ── Rate limiting ──────────────────────────────────────────────────────────
  const ip = getClientIp(req)
  const rl = checkRateLimit(`azure:${ip}`, PHI4_RATE_LIMIT, PHI4_RATE_WINDOW_MS)
  if (!rl.allowed) {
    return NextResponse.json(
      { error: 'Too many requests. Please wait a moment before trying again.' },
      {
        status: 429,
        headers: { 'Retry-After': String(Math.ceil((rl.resetAt - Date.now()) / 1000)) },
      },
    )
  }

  // ── Origin guard ───────────────────────────────────────────────────────────
  const origin = req.headers.get('origin')
  const host = req.headers.get('host')
  if (origin && host && !origin.includes(host)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  try {
    const body = await req.json()
    const { intent, language, projectContext, previousCode, isVoiceCommand, stream } = body

    if (!intent || !language) {
      return NextResponse.json({ error: 'Missing intent or language' }, { status: 400 })
    }

    const payloadSize = JSON.stringify(body).length
    if (payloadSize > PHI4_MAX_PAYLOAD_BYTES) {
      return NextResponse.json({ error: 'Request payload too large' }, { status: 413 })
    }

    const endpoint = process.env.AZURE_FOUNDRY_ENDPOINT
    const apiKey   = process.env.AZURE_FOUNDRY_API_KEY
    if (!endpoint || !apiKey) {
      return NextResponse.json(
        { error: 'AZURE_FOUNDRY_ENDPOINT or AZURE_FOUNDRY_API_KEY not configured' },
        { status: 500 },
      )
    }

    const deployment = process.env.AZURE_FOUNDRY_DEPLOYMENT ?? PHI4_DEFAULT_DEPLOYMENT
    const maxTokens  = Math.min(
      PHI4_MAX_TOKENS_HARD_CAP,
      parseInt(process.env.PHI4_MAX_TOKENS || String(PHI4_DEFAULT_MAX_TOKENS), 10) || PHI4_DEFAULT_MAX_TOKENS,
    )

    const openai = new OpenAI({
      baseURL: endpoint.replace(/\/$/, ''),
      apiKey,
    })

    const systemPrompt = buildSystemPrompt(language as Language)
    const userMessage  = isVoiceCommand && previousCode
      ? buildVoiceCommandPrompt(intent, previousCode, language as Language)
      : projectContext
        ? `Project context: ${projectContext}\n\nRequest: ${intent}`
        : intent

    const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
      { role: 'system', content: systemPrompt },
      { role: 'user',   content: userMessage  },
    ]

    // ── Streaming ─────────────────────────────────────────────────────────────
    if (stream) {
      const streamResponse = await openai.chat.completions.create({
        model: deployment,
        messages,
        max_tokens: maxTokens,
        temperature: 0.2,
        stream: true,
      })

      const encoder = new TextEncoder()
      const readable = new ReadableStream({
        async start(controller) {
          try {
            for await (const chunk of streamResponse) {
              controller.enqueue(encoder.encode(`data: ${JSON.stringify(chunk)}\n\n`))
            }
            controller.enqueue(encoder.encode('data: [DONE]\n\n'))
          } finally {
            controller.close()
          }
        },
      })

      return new Response(readable, {
        status: 200,
        headers: {
          'Content-Type': 'text/event-stream; charset=utf-8',
          'Cache-Control': 'no-cache, no-transform',
          Connection: 'keep-alive',
        },
      })
    }

    // ── Non-streaming ─────────────────────────────────────────────────────────
    const completion = await openai.chat.completions.create({
      model: deployment,
      messages,
      max_tokens: maxTokens,
      temperature: 0.2,
    })

    const rawContent = completion.choices[0]?.message?.content ?? ''

    let parsed: { code: string; summary: string; language: string }
    try {
      const clean = rawContent.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
      parsed = JSON.parse(clean)
    } catch {
      parsed = {
        code: rawContent,
        summary: 'Code generated by Phi-4. Review for accessibility compliance.',
        language,
      }
    }

    return NextResponse.json({
      code: parsed.code,
      summary: parsed.summary,
      language: parsed.language || language,
    })
  } catch (err) {
    // Surface upstream HTTP errors (429, 503, etc.) with their real status + Retry-After
    if (err instanceof OpenAI.APIError) {
      console.error(`Azure Phi-4 upstream error ${err.status}:`, err.message)
      const retryAfter = err.headers?.get?.('retry-after') ?? err.headers?.['retry-after']
      const resetSeconds = err.headers?.get?.('x-ratelimit-reset-requests') ?? err.headers?.['x-ratelimit-reset-requests']
      const waitSeconds = retryAfter ?? resetSeconds ?? '60'
      const headers: Record<string, string> = { 'Retry-After': String(waitSeconds) }
      return NextResponse.json(
        { error: err.message || `Azure error (${err.status})` },
        { status: err.status ?? 500, headers },
      )
    }
    console.error('Azure Phi-4 route error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
